app = "mm-eng-translator-kxgba"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  NODE_ENV = "production"

[deploy]
  strategy = "immediate"
  release_command = "echo 'Starting deployment...'"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[http_service.checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "40s"
    method = "GET"
    path = "/api/health"
    protocol = "http"
    tls_skip_verify = true

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1

[metrics]
  port = 8080
  path = "/metrics" 