app = "mmlater"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "3000"
  NODE_ENV = "production"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = "10s"
    timeout = "3s"
    grace_period = "10s"
    method = "GET"
    path = "/api/health"
    protocol = "http"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "256mb" 