app = "mm-eng-translator-kxgba"
primary_region = "sin"  # Singapore region, you can change this

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  NODE_ENV = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    interval = "10s"
    timeout = "5s"
    grace_period = "30s"
    method = "GET"
    path = "/api/health"
    protocol = "http"
    tls_skip_verify = true

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256 